// <auto-generated />
namespace HaterDateApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class useridtostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useridtostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201503242156069_userid to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
